/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controladores.ControladorCandidatos;
import javax.swing.JDialog;
import javax.swing.JRadioButton;
import javax.swing.JButton;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class MenuCandidatos extends javax.swing.JFrame {

    /**
     * Creates new form MenuCandidatos
     */
    public MenuCandidatos() {
        initComponents();
    }
    
    ControladorCandidatos cc = ControladorCandidatos.getInstance();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoAddCand = new javax.swing.JButton();
        botaoExPres = new javax.swing.JButton();
        botaoEncontrarPres = new javax.swing.JButton();
        botaoMostraPresidente = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoEncontraGov = new javax.swing.JButton();
        botaoEncontraDep = new javax.swing.JButton();
        botaoMostraGov = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botaoExGov = new javax.swing.JButton();
        botaoExDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Área dos Candidatos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 255, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Menu dos Candidatos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        botaoAddCand.setText("Adicionar Candidatos");
        botaoAddCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddCandActionPerformed(evt);
            }
        });

        botaoExPres.setText("Excluir Presidente");
        botaoExPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExPresActionPerformed(evt);
            }
        });

        botaoEncontrarPres.setText("Encontrar Presidente");
        botaoEncontrarPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncontrarPresActionPerformed(evt);
            }
        });

        botaoMostraPresidente.setText("Mostrar Presidentes");
        botaoMostraPresidente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                botaoMostraPresidenteComponentShown(evt);
            }
        });
        botaoMostraPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMostraPresidenteActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoEncontraGov.setText("Encontrar Goverrnador");
        botaoEncontraGov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncontraGovActionPerformed(evt);
            }
        });

        botaoEncontraDep.setText("Encontrar Deputado");
        botaoEncontraDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncontraDepActionPerformed(evt);
            }
        });

        botaoMostraGov.setText("Mostrar Governadores");
        botaoMostraGov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMostraGovActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar Deputados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoExGov.setText("Excluir Governador");
        botaoExGov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExGovActionPerformed(evt);
            }
        });

        botaoExDep.setText("Excluir Deputado");
        botaoExDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botaoAddCand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEncontraDep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEncontraGov, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEncontrarPres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoExGov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMostraPresidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMostraGov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExPres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddCand)
                    .addComponent(botaoMostraPresidente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEncontrarPres)
                    .addComponent(botaoMostraGov))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEncontraGov)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoExPres)
                    .addComponent(botaoEncontraDep))
                .addGap(18, 18, 18)
                .addComponent(botaoExGov)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoExDep))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExPresActionPerformed
        String nomePresidente = JOptionPane.showInputDialog("Digite o nome do Presidente a ser excluido:");
        if(cc.excluirPresidente(nomePresidente) == true)
            JOptionPane.showMessageDialog(null, "Presidente foi excluído com sucesso");
        else
            JOptionPane.showMessageDialog(null, "Presidente não encontrado, favor tentar novamente");
    }//GEN-LAST:event_botaoExPresActionPerformed

    private void botaoAddCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddCandActionPerformed
        TelaAdicionarCandidato obj = new TelaAdicionarCandidato();
        this.dispose();
        obj.setVisible(true);
    }//GEN-LAST:event_botaoAddCandActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        MenuConfiguracoes obj = new MenuConfiguracoes();
        this.dispose();
        obj.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoMostraPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMostraPresidenteActionPerformed
        cc.retornaPresidente();
    }//GEN-LAST:event_botaoMostraPresidenteActionPerformed

    private void botaoMostraPresidenteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_botaoMostraPresidenteComponentShown

    }//GEN-LAST:event_botaoMostraPresidenteComponentShown

    private void botaoEncontrarPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncontrarPresActionPerformed
        String nomePresidente = JOptionPane.showInputDialog("Digite o nome do Presidente a ser encontrado:");
        cc.encontrarPresidente(nomePresidente);
    }//GEN-LAST:event_botaoEncontrarPresActionPerformed

    private void botaoMostraGovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMostraGovActionPerformed
        cc.retornaGovernador();
    }//GEN-LAST:event_botaoMostraGovActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cc.retornaDeputado();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoExGovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExGovActionPerformed
        String nomeGovernador = JOptionPane.showInputDialog("Digite o nome do Governador a ser excluido:");
        if(cc.excluirGovernador(nomeGovernador) == true)
            JOptionPane.showMessageDialog(null, "Governador foi excluído com sucesso");
        else
            JOptionPane.showMessageDialog(null, "Governador não encontrado, favor tentar novamente");
    }//GEN-LAST:event_botaoExGovActionPerformed

    private void botaoExDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExDepActionPerformed
        String nomeDeputado = JOptionPane.showInputDialog("Digite o nome do Deputado a ser excluido:");
        if(cc.excluirDeputado(nomeDeputado) == true)
            JOptionPane.showMessageDialog(null, "Deputado foi excluído com sucesso");
        else
            JOptionPane.showMessageDialog(null, "Deputado não encontrado, favor tentar novamente");
    }//GEN-LAST:event_botaoExDepActionPerformed

    private void botaoEncontraGovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncontraGovActionPerformed
        String nomeGov = JOptionPane.showInputDialog("Digite o nome do Governador a ser encontrado:");
        cc.encontrarGovernador(nomeGov);
    }//GEN-LAST:event_botaoEncontraGovActionPerformed

    private void botaoEncontraDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncontraDepActionPerformed
        String nomeDep = JOptionPane.showInputDialog("Digite o nome do Deputado a ser encontrado:");
        cc.encontrarDeputado(nomeDep);
    }//GEN-LAST:event_botaoEncontraDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCandidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddCand;
    private javax.swing.JButton botaoEncontraDep;
    private javax.swing.JButton botaoEncontraGov;
    private javax.swing.JButton botaoEncontrarPres;
    private javax.swing.JButton botaoExDep;
    private javax.swing.JButton botaoExGov;
    private javax.swing.JButton botaoExPres;
    private javax.swing.JButton botaoMostraGov;
    private javax.swing.JButton botaoMostraPresidente;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
